services:
  backend:
    build: 
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: 
      context: ./memoryReactFrontEnd
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./memoryReactFrontEnd:/app
      - /app/node_modules