# Generated by Django 4.2.16 on 2024-11-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memoryAPI", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="birth",
            field=models.IntegerField(),
        ),
    ]
